version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 1
    working_directory: ~/lastfm
    steps:
      - checkout
      - attach_workspace:
          at: ~/lastfm
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Running tests
          command: yarn test:coverage
      - codecov/upload:
          name: Uploading coverage
          file: ~/lastfm/coverage/*.json

workflows:
  version: 2
  ci:
    jobs:
      - test
