version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 1
    working_directory: ~/lastfm
    steps:
      - checkout
      - attach_workspace:
          at: ~/lastfm
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Testing project
          command: yarn test

workflows:
  version: 2
  ci:
    jobs:
      - test
