version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn test:coverage

workflows:
  version: 2
  ci:
    jobs:
      - test
